# Generated by Django 3.1.1 on 2021-10-07 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(70, message='La edad no puede ser superior a 70 años'), django.core.validators.MinValueValidator(5, message='La edad no puede ser menor a 5 años')], verbose_name='Edad'),
        ),
    ]
