# Generated by Django 3.1.1 on 2021-10-07 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sexo', '0001_initial'),
        ('donante', '0002_auto_20211007_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Sexo', to='sexo.sexos', verbose_name='Sexo'),
        ),
    ]
