# Generated by Django 3.1.1 on 2021-09-29 13:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=20, unique=True, verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(choices=[('ISL', 'Isla de la juventud'), ('PRI', 'Pinar del río'), ('LHA', 'La Habana'), ('MAY', 'Mayabeque'), ('ART', 'Artemisa'), ('MAT', 'Matanzas'), ('CAV', 'Ciego de Ávila'), ('CFG', 'Cienfuegos'), ('CAM', 'Camaguey'), ('Las tunas', 'Las tunas'), ('Granma', 'Granma'), ('HOL', 'Holguín'), ('SCU', 'Santiago de Cuba'), ('GTM', 'Guantánamo')], max_length=20, unique=True, verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Gary', 'Gary')], max_length=9, unique=True, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('ci', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', message='Carné incorrecto'), django.core.validators.MinLengthValidator(11, message='El carné debe contener 11 caracteres')], verbose_name='Carnet de identidad')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(25, message='La edad no puede ser superior a 25 años'), django.core.validators.MinValueValidator(5, message='La edad no puede ser menor a 5 años')], verbose_name='Edad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_by', to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.municipio', verbose_name='Municipio')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.provincia', verbose_name='Provincia')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sexo', verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
