# Generated by Django 3.1.1 on 2021-10-04 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(80, message='La edad no puede ser superior a 80 años'), django.core.validators.MinValueValidator(18, message='La edad no puede ser menor a 18 años')], verbose_name='Edad'),
        ),
    ]
