# Generated by Django 3.1.1 on 2021-10-02 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areasalud', '0002_auto_20211002_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('direccion', models.TextField(max_length=200, verbose_name='Direccion')),
                ('areasalud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='areasalud.areasalud', verbose_name='AreaSalud')),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
            },
        ),
    ]
