# Generated by Django 3.1.1 on 2021-10-01 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provincia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=20, unique=True, verbose_name='Municipio')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provincia.provincias', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
    ]
