# Generated by Django 3.1.1 on 2021-10-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkinColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skincolor', models.CharField(max_length=15, unique=True, verbose_name='Color de la Piel')),
            ],
            options={
                'verbose_name': 'Skincolor',
                'verbose_name_plural': 'Skincolors',
            },
        ),
    ]
