# Generated by Django 3.1.1 on 2021-10-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skincolor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skincolor',
            old_name='skincolor',
            new_name='nskincolor',
        ),
    ]
