# Generated by Django 3.1.1 on 2021-10-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areasalud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasalud',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
    ]
