# Generated by Django 3.1.1 on 2021-09-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(choices=[('ISL', 'Isla de la juventud'), ('PRI', 'Pinar del río'), ('LHA', 'La Habana'), ('MAY', 'Mayabeque'), ('ART', 'Artemisa'), ('MAT', 'Matanzas'), ('CAV', 'Ciego de Ávila'), ('CFG', 'Cienfuegos'), ('CAM', 'Camaguey'), ('Las tunas', 'Las tunas'), ('Granma', 'Granma'), ('HOL', 'Holguín'), ('SCU', 'Santiago de Cuba'), ('GTM', 'Guantánamo')], max_length=25, unique=True, verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
    ]
