# Generated by Django 3.1.1 on 2021-10-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincias',
            name='provincia',
            field=models.CharField(choices=[('Isla de la juventud', 'Isla de la juventud'), ('Pinar del río', 'Pinar del río'), ('La Habana', 'La Habana'), ('Mayabeque', 'Mayabeque'), ('Artemisa', 'Artemisa'), ('Matanzas', 'Matanzas'), ('Ciego de Ávila', 'Ciego de Ávila'), ('Cienfuegos', 'Cienfuegos'), ('Camaguey', 'Camaguey'), ('Las tunas', 'Las tunas'), ('Granma', 'Granma'), ('Holguín', 'Holguín'), ('Santiago de Cuba', 'Santiago de Cuba'), ('Guantánamo', 'Guantánamo')], max_length=25, unique=True, verbose_name='Provincia'),
        ),
    ]
