# Generated by Django 3.1.1 on 2021-10-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodgroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, unique=True, verbose_name='Grupo Sanguineo'),
        ),
    ]
