# Generated by Django 3.1.1 on 2021-10-07 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donante', '0002_auto_20211007_2019'),
        ('bloodbank', '0002_auto_20211002_0849'),
        ('consultorio', '0002_auto_20211004_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de la donación')),
                ('observaciones', models.TextField(blank=True, max_length=500, verbose_name='Observaciones')),
                ('bloodbank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BloodBank', to='bloodbank.bloodbank', verbose_name='BloodBank')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Donacion.consultorio+', to='consultorio.consultorio', verbose_name='Consultorio')),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Donante', to='donante.donante', verbose_name='Donante')),
            ],
            options={
                'verbose_name': 'Donacion',
                'verbose_name_plural': 'Donaciones',
            },
        ),
    ]
