# Generated by Django 3.1.1 on 2021-10-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='observaciones',
            field=models.TextField(blank=True, default='Sin observaciones', max_length=500, verbose_name='Observaciones'),
        ),
    ]
