# Generated by Django 3.1.1 on 2021-10-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_auto_20211002_0849'),
        ('donacion', '0002_auto_20211007_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='bloodbank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BloodBank', to='bloodbank.bloodbank', verbose_name='Banco de Sangre'),
        ),
    ]
